package com.example.videohttp.module;

import java.io.Serializable;

public class TLive implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.userId
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.liveTitle
     *
     * @mbg.generated
     */
    private String liveTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.liveIcon
     *
     * @mbg.generated
     */
    private String liveIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.liveAddress
     *
     * @mbg.generated
     */
    private String liveAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.liveStatus
     *
     * @mbg.generated
     */
    private Integer liveStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.liveHdAddress
     *
     * @mbg.generated
     */
    private String liveHdAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.liveSdAddress
     *
     * @mbg.generated
     */
    private String liveSdAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.liveDescription
     *
     * @mbg.generated
     */
    private String liveDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.liveLdAddress
     *
     * @mbg.generated
     */
    private String liveLdAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_live
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.id
     *
     * @return the value of v_live.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.id
     *
     * @param id the value for v_live.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.userId
     *
     * @return the value of v_live.userId
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.userId
     *
     * @param userId the value for v_live.userId
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.liveTitle
     *
     * @return the value of v_live.liveTitle
     *
     * @mbg.generated
     */
    public String getLiveTitle() {
        return liveTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.liveTitle
     *
     * @param liveTitle the value for v_live.liveTitle
     *
     * @mbg.generated
     */
    public void setLiveTitle(String liveTitle) {
        this.liveTitle = liveTitle == null ? null : liveTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.liveIcon
     *
     * @return the value of v_live.liveIcon
     *
     * @mbg.generated
     */
    public String getLiveIcon() {
        return liveIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.liveIcon
     *
     * @param liveIcon the value for v_live.liveIcon
     *
     * @mbg.generated
     */
    public void setLiveIcon(String liveIcon) {
        this.liveIcon = liveIcon == null ? null : liveIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.liveAddress
     *
     * @return the value of v_live.liveAddress
     *
     * @mbg.generated
     */
    public String getLiveAddress() {
        return liveAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.liveAddress
     *
     * @param liveAddress the value for v_live.liveAddress
     *
     * @mbg.generated
     */
    public void setLiveAddress(String liveAddress) {
        this.liveAddress = liveAddress == null ? null : liveAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.liveStatus
     *
     * @return the value of v_live.liveStatus
     *
     * @mbg.generated
     */
    public Integer getLiveStatus() {
        return liveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.liveStatus
     *
     * @param liveStatus the value for v_live.liveStatus
     *
     * @mbg.generated
     */
    public void setLiveStatus(Integer liveStatus) {
        this.liveStatus = liveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.liveHdAddress
     *
     * @return the value of v_live.liveHdAddress
     *
     * @mbg.generated
     */
    public String getLiveHdAddress() {
        return liveHdAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.liveHdAddress
     *
     * @param liveHdAddress the value for v_live.liveHdAddress
     *
     * @mbg.generated
     */
    public void setLiveHdAddress(String liveHdAddress) {
        this.liveHdAddress = liveHdAddress == null ? null : liveHdAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.liveSdAddress
     *
     * @return the value of v_live.liveSdAddress
     *
     * @mbg.generated
     */
    public String getLiveSdAddress() {
        return liveSdAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.liveSdAddress
     *
     * @param liveSdAddress the value for v_live.liveSdAddress
     *
     * @mbg.generated
     */
    public void setLiveSdAddress(String liveSdAddress) {
        this.liveSdAddress = liveSdAddress == null ? null : liveSdAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.liveDescription
     *
     * @return the value of v_live.liveDescription
     *
     * @mbg.generated
     */
    public String getLiveDescription() {
        return liveDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.liveDescription
     *
     * @param liveDescription the value for v_live.liveDescription
     *
     * @mbg.generated
     */
    public void setLiveDescription(String liveDescription) {
        this.liveDescription = liveDescription == null ? null : liveDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.liveLdAddress
     *
     * @return the value of v_live.liveLdAddress
     *
     * @mbg.generated
     */
    public String getLiveLdAddress() {
        return liveLdAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.liveLdAddress
     *
     * @param liveLdAddress the value for v_live.liveLdAddress
     *
     * @mbg.generated
     */
    public void setLiveLdAddress(String liveLdAddress) {
        this.liveLdAddress = liveLdAddress == null ? null : liveLdAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_live
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TLive other = (TLive) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getLiveTitle() == null ? other.getLiveTitle() == null : this.getLiveTitle().equals(other.getLiveTitle()))
            && (this.getLiveIcon() == null ? other.getLiveIcon() == null : this.getLiveIcon().equals(other.getLiveIcon()))
            && (this.getLiveAddress() == null ? other.getLiveAddress() == null : this.getLiveAddress().equals(other.getLiveAddress()))
            && (this.getLiveStatus() == null ? other.getLiveStatus() == null : this.getLiveStatus().equals(other.getLiveStatus()))
            && (this.getLiveHdAddress() == null ? other.getLiveHdAddress() == null : this.getLiveHdAddress().equals(other.getLiveHdAddress()))
            && (this.getLiveSdAddress() == null ? other.getLiveSdAddress() == null : this.getLiveSdAddress().equals(other.getLiveSdAddress()))
            && (this.getLiveDescription() == null ? other.getLiveDescription() == null : this.getLiveDescription().equals(other.getLiveDescription()))
            && (this.getLiveLdAddress() == null ? other.getLiveLdAddress() == null : this.getLiveLdAddress().equals(other.getLiveLdAddress()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_live
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getLiveTitle() == null) ? 0 : getLiveTitle().hashCode());
        result = prime * result + ((getLiveIcon() == null) ? 0 : getLiveIcon().hashCode());
        result = prime * result + ((getLiveAddress() == null) ? 0 : getLiveAddress().hashCode());
        result = prime * result + ((getLiveStatus() == null) ? 0 : getLiveStatus().hashCode());
        result = prime * result + ((getLiveHdAddress() == null) ? 0 : getLiveHdAddress().hashCode());
        result = prime * result + ((getLiveSdAddress() == null) ? 0 : getLiveSdAddress().hashCode());
        result = prime * result + ((getLiveDescription() == null) ? 0 : getLiveDescription().hashCode());
        result = prime * result + ((getLiveLdAddress() == null) ? 0 : getLiveLdAddress().hashCode());
        return result;
    }
}