package com.example.videohttp.module;

import java.io.Serializable;

public class TLive implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.userId
     *
     * @mbg.generated
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.liveTitle
     *
     * @mbg.generated
     */
    private String livetitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.liveIcon
     *
     * @mbg.generated
     */
    private String liveicon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.liveAddress
     *
     * @mbg.generated
     */
    private String liveaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.liveStatus
     *
     * @mbg.generated
     */
    private Integer livestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.liveHdAddress
     *
     * @mbg.generated
     */
    private String livehdaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.liveLdAddress
     *
     * @mbg.generated
     */
    private String liveldaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.liveSdAddress
     *
     * @mbg.generated
     */
    private String livesdaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_live.liveDescription
     *
     * @mbg.generated
     */
    private String livedescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_live
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.id
     *
     * @return the value of v_live.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.id
     *
     * @param id the value for v_live.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.userId
     *
     * @return the value of v_live.userId
     *
     * @mbg.generated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.userId
     *
     * @param userid the value for v_live.userId
     *
     * @mbg.generated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.liveTitle
     *
     * @return the value of v_live.liveTitle
     *
     * @mbg.generated
     */
    public String getLivetitle() {
        return livetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.liveTitle
     *
     * @param livetitle the value for v_live.liveTitle
     *
     * @mbg.generated
     */
    public void setLivetitle(String livetitle) {
        this.livetitle = livetitle == null ? null : livetitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.liveIcon
     *
     * @return the value of v_live.liveIcon
     *
     * @mbg.generated
     */
    public String getLiveicon() {
        return liveicon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.liveIcon
     *
     * @param liveicon the value for v_live.liveIcon
     *
     * @mbg.generated
     */
    public void setLiveicon(String liveicon) {
        this.liveicon = liveicon == null ? null : liveicon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.liveAddress
     *
     * @return the value of v_live.liveAddress
     *
     * @mbg.generated
     */
    public String getLiveaddress() {
        return liveaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.liveAddress
     *
     * @param liveaddress the value for v_live.liveAddress
     *
     * @mbg.generated
     */
    public void setLiveaddress(String liveaddress) {
        this.liveaddress = liveaddress == null ? null : liveaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.liveStatus
     *
     * @return the value of v_live.liveStatus
     *
     * @mbg.generated
     */
    public Integer getLivestatus() {
        return livestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.liveStatus
     *
     * @param livestatus the value for v_live.liveStatus
     *
     * @mbg.generated
     */
    public void setLivestatus(Integer livestatus) {
        this.livestatus = livestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.liveHdAddress
     *
     * @return the value of v_live.liveHdAddress
     *
     * @mbg.generated
     */
    public String getLivehdaddress() {
        return livehdaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.liveHdAddress
     *
     * @param livehdaddress the value for v_live.liveHdAddress
     *
     * @mbg.generated
     */
    public void setLivehdaddress(String livehdaddress) {
        this.livehdaddress = livehdaddress == null ? null : livehdaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.liveLdAddress
     *
     * @return the value of v_live.liveLdAddress
     *
     * @mbg.generated
     */
    public String getLiveldaddress() {
        return liveldaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.liveLdAddress
     *
     * @param liveldaddress the value for v_live.liveLdAddress
     *
     * @mbg.generated
     */
    public void setLiveldaddress(String liveldaddress) {
        this.liveldaddress = liveldaddress == null ? null : liveldaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.liveSdAddress
     *
     * @return the value of v_live.liveSdAddress
     *
     * @mbg.generated
     */
    public String getLivesdaddress() {
        return livesdaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.liveSdAddress
     *
     * @param livesdaddress the value for v_live.liveSdAddress
     *
     * @mbg.generated
     */
    public void setLivesdaddress(String livesdaddress) {
        this.livesdaddress = livesdaddress == null ? null : livesdaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_live.liveDescription
     *
     * @return the value of v_live.liveDescription
     *
     * @mbg.generated
     */
    public String getLivedescription() {
        return livedescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_live.liveDescription
     *
     * @param livedescription the value for v_live.liveDescription
     *
     * @mbg.generated
     */
    public void setLivedescription(String livedescription) {
        this.livedescription = livedescription == null ? null : livedescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_live
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TLive other = (TLive) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getLivetitle() == null ? other.getLivetitle() == null : this.getLivetitle().equals(other.getLivetitle()))
            && (this.getLiveicon() == null ? other.getLiveicon() == null : this.getLiveicon().equals(other.getLiveicon()))
            && (this.getLiveaddress() == null ? other.getLiveaddress() == null : this.getLiveaddress().equals(other.getLiveaddress()))
            && (this.getLivestatus() == null ? other.getLivestatus() == null : this.getLivestatus().equals(other.getLivestatus()))
            && (this.getLivehdaddress() == null ? other.getLivehdaddress() == null : this.getLivehdaddress().equals(other.getLivehdaddress()))
            && (this.getLiveldaddress() == null ? other.getLiveldaddress() == null : this.getLiveldaddress().equals(other.getLiveldaddress()))
            && (this.getLivesdaddress() == null ? other.getLivesdaddress() == null : this.getLivesdaddress().equals(other.getLivesdaddress()))
            && (this.getLivedescription() == null ? other.getLivedescription() == null : this.getLivedescription().equals(other.getLivedescription()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_live
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getLivetitle() == null) ? 0 : getLivetitle().hashCode());
        result = prime * result + ((getLiveicon() == null) ? 0 : getLiveicon().hashCode());
        result = prime * result + ((getLiveaddress() == null) ? 0 : getLiveaddress().hashCode());
        result = prime * result + ((getLivestatus() == null) ? 0 : getLivestatus().hashCode());
        result = prime * result + ((getLivehdaddress() == null) ? 0 : getLivehdaddress().hashCode());
        result = prime * result + ((getLiveldaddress() == null) ? 0 : getLiveldaddress().hashCode());
        result = prime * result + ((getLivesdaddress() == null) ? 0 : getLivesdaddress().hashCode());
        result = prime * result + ((getLivedescription() == null) ? 0 : getLivedescription().hashCode());
        return result;
    }
}