package com.example.videohttp.module;

import java.io.Serializable;
import java.util.Date;

public class TSrs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_srs.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_srs.action
     *
     * @mbg.generated
     */
    private String action;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_srs.client_id
     *
     * @mbg.generated
     */
    private Integer clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_srs.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_srs.vhost
     *
     * @mbg.generated
     */
    private String vhost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_srs.app
     *
     * @mbg.generated
     */
    private String app;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_srs.custom
     *
     * @mbg.generated
     */
    private String custom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_srs.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_srs
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_srs.id
     *
     * @return the value of v_srs.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_srs.id
     *
     * @param id the value for v_srs.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_srs.action
     *
     * @return the value of v_srs.action
     *
     * @mbg.generated
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_srs.action
     *
     * @param action the value for v_srs.action
     *
     * @mbg.generated
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_srs.client_id
     *
     * @return the value of v_srs.client_id
     *
     * @mbg.generated
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_srs.client_id
     *
     * @param clientId the value for v_srs.client_id
     *
     * @mbg.generated
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_srs.ip
     *
     * @return the value of v_srs.ip
     *
     * @mbg.generated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_srs.ip
     *
     * @param ip the value for v_srs.ip
     *
     * @mbg.generated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_srs.vhost
     *
     * @return the value of v_srs.vhost
     *
     * @mbg.generated
     */
    public String getVhost() {
        return vhost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_srs.vhost
     *
     * @param vhost the value for v_srs.vhost
     *
     * @mbg.generated
     */
    public void setVhost(String vhost) {
        this.vhost = vhost == null ? null : vhost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_srs.app
     *
     * @return the value of v_srs.app
     *
     * @mbg.generated
     */
    public String getApp() {
        return app;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_srs.app
     *
     * @param app the value for v_srs.app
     *
     * @mbg.generated
     */
    public void setApp(String app) {
        this.app = app == null ? null : app.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_srs.custom
     *
     * @return the value of v_srs.custom
     *
     * @mbg.generated
     */
    public String getCustom() {
        return custom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_srs.custom
     *
     * @param custom the value for v_srs.custom
     *
     * @mbg.generated
     */
    public void setCustom(String custom) {
        this.custom = custom == null ? null : custom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_srs.createTime
     *
     * @return the value of v_srs.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_srs.createTime
     *
     * @param createtime the value for v_srs.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_srs
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TSrs other = (TSrs) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAction() == null ? other.getAction() == null : this.getAction().equals(other.getAction()))
            && (this.getClientId() == null ? other.getClientId() == null : this.getClientId().equals(other.getClientId()))
            && (this.getIp() == null ? other.getIp() == null : this.getIp().equals(other.getIp()))
            && (this.getVhost() == null ? other.getVhost() == null : this.getVhost().equals(other.getVhost()))
            && (this.getApp() == null ? other.getApp() == null : this.getApp().equals(other.getApp()))
            && (this.getCustom() == null ? other.getCustom() == null : this.getCustom().equals(other.getCustom()))
            && (this.getCreatetime() == null ? other.getCreatetime() == null : this.getCreatetime().equals(other.getCreatetime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_srs
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAction() == null) ? 0 : getAction().hashCode());
        result = prime * result + ((getClientId() == null) ? 0 : getClientId().hashCode());
        result = prime * result + ((getIp() == null) ? 0 : getIp().hashCode());
        result = prime * result + ((getVhost() == null) ? 0 : getVhost().hashCode());
        result = prime * result + ((getApp() == null) ? 0 : getApp().hashCode());
        result = prime * result + ((getCustom() == null) ? 0 : getCustom().hashCode());
        result = prime * result + ((getCreatetime() == null) ? 0 : getCreatetime().hashCode());
        return result;
    }
}