package com.example.videohttp.module;

import java.io.Serializable;

public class TUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.userName
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.userAge
     *
     * @mbg.generated
     */
    private Integer userAge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.userPhone
     *
     * @mbg.generated
     */
    private String userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.userEmail
     *
     * @mbg.generated
     */
    private String userEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.userPassword
     *
     * @mbg.generated
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.userCreateTime
     *
     * @mbg.generated
     */
    private String userCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.userBirthDay
     *
     * @mbg.generated
     */
    private String userBirthDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.userSex
     *
     * @mbg.generated
     */
    private Boolean userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_user.userIcon
     *
     * @mbg.generated
     */
    private String userIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table v_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.id
     *
     * @return the value of v_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.id
     *
     * @param id the value for v_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.userName
     *
     * @return the value of v_user.userName
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.userName
     *
     * @param userName the value for v_user.userName
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.userAge
     *
     * @return the value of v_user.userAge
     *
     * @mbg.generated
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.userAge
     *
     * @param userAge the value for v_user.userAge
     *
     * @mbg.generated
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.userPhone
     *
     * @return the value of v_user.userPhone
     *
     * @mbg.generated
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.userPhone
     *
     * @param userPhone the value for v_user.userPhone
     *
     * @mbg.generated
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.userEmail
     *
     * @return the value of v_user.userEmail
     *
     * @mbg.generated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.userEmail
     *
     * @param userEmail the value for v_user.userEmail
     *
     * @mbg.generated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.userPassword
     *
     * @return the value of v_user.userPassword
     *
     * @mbg.generated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.userPassword
     *
     * @param userPassword the value for v_user.userPassword
     *
     * @mbg.generated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.userCreateTime
     *
     * @return the value of v_user.userCreateTime
     *
     * @mbg.generated
     */
    public String getUserCreateTime() {
        return userCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.userCreateTime
     *
     * @param userCreateTime the value for v_user.userCreateTime
     *
     * @mbg.generated
     */
    public void setUserCreateTime(String userCreateTime) {
        this.userCreateTime = userCreateTime == null ? null : userCreateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.userBirthDay
     *
     * @return the value of v_user.userBirthDay
     *
     * @mbg.generated
     */
    public String getUserBirthDay() {
        return userBirthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.userBirthDay
     *
     * @param userBirthDay the value for v_user.userBirthDay
     *
     * @mbg.generated
     */
    public void setUserBirthDay(String userBirthDay) {
        this.userBirthDay = userBirthDay == null ? null : userBirthDay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.userSex
     *
     * @return the value of v_user.userSex
     *
     * @mbg.generated
     */
    public Boolean getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.userSex
     *
     * @param userSex the value for v_user.userSex
     *
     * @mbg.generated
     */
    public void setUserSex(Boolean userSex) {
        this.userSex = userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_user.userIcon
     *
     * @return the value of v_user.userIcon
     *
     * @mbg.generated
     */
    public String getUserIcon() {
        return userIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_user.userIcon
     *
     * @param userIcon the value for v_user.userIcon
     *
     * @mbg.generated
     */
    public void setUserIcon(String userIcon) {
        this.userIcon = userIcon == null ? null : userIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TUser other = (TUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getUserAge() == null ? other.getUserAge() == null : this.getUserAge().equals(other.getUserAge()))
            && (this.getUserPhone() == null ? other.getUserPhone() == null : this.getUserPhone().equals(other.getUserPhone()))
            && (this.getUserEmail() == null ? other.getUserEmail() == null : this.getUserEmail().equals(other.getUserEmail()))
            && (this.getUserPassword() == null ? other.getUserPassword() == null : this.getUserPassword().equals(other.getUserPassword()))
            && (this.getUserCreateTime() == null ? other.getUserCreateTime() == null : this.getUserCreateTime().equals(other.getUserCreateTime()))
            && (this.getUserBirthDay() == null ? other.getUserBirthDay() == null : this.getUserBirthDay().equals(other.getUserBirthDay()))
            && (this.getUserSex() == null ? other.getUserSex() == null : this.getUserSex().equals(other.getUserSex()))
            && (this.getUserIcon() == null ? other.getUserIcon() == null : this.getUserIcon().equals(other.getUserIcon()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getUserAge() == null) ? 0 : getUserAge().hashCode());
        result = prime * result + ((getUserPhone() == null) ? 0 : getUserPhone().hashCode());
        result = prime * result + ((getUserEmail() == null) ? 0 : getUserEmail().hashCode());
        result = prime * result + ((getUserPassword() == null) ? 0 : getUserPassword().hashCode());
        result = prime * result + ((getUserCreateTime() == null) ? 0 : getUserCreateTime().hashCode());
        result = prime * result + ((getUserBirthDay() == null) ? 0 : getUserBirthDay().hashCode());
        result = prime * result + ((getUserSex() == null) ? 0 : getUserSex().hashCode());
        result = prime * result + ((getUserIcon() == null) ? 0 : getUserIcon().hashCode());
        return result;
    }
}