package com.example.videohttp.mapper;

import com.example.videohttp.module.TLiveHistory;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TLiveHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_liveHistory
     *
     * @mbg.generated
     */
    @Delete({
        "delete from v_liveHistory",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_liveHistory
     *
     * @mbg.generated
     */
    @Insert({
        "insert into v_liveHistory (id, createTime, ",
        "filePath, userId)",
        "values (#{id,jdbcType=INTEGER}, #{createtime,jdbcType=TIMESTAMP}, ",
        "#{filepath,jdbcType=VARCHAR}, #{userid,jdbcType=INTEGER})"
    })
    int insert(TLiveHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_liveHistory
     *
     * @mbg.generated
     */
    @InsertProvider(type=TLiveHistorySqlProvider.class, method="insertSelective")
    int insertSelective(TLiveHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_liveHistory
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, createTime, filePath, userId",
        "from v_liveHistory",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="createTime", property="createtime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="filePath", property="filepath", jdbcType=JdbcType.VARCHAR),
        @Result(column="userId", property="userid", jdbcType=JdbcType.INTEGER)
    })
    TLiveHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_liveHistory
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TLiveHistorySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TLiveHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_liveHistory
     *
     * @mbg.generated
     */
    @Update({
        "update v_liveHistory",
        "set createTime = #{createtime,jdbcType=TIMESTAMP},",
          "filePath = #{filepath,jdbcType=VARCHAR},",
          "userId = #{userid,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TLiveHistory record);
}