package com.example.videohttp.mapper;

import com.example.videohttp.module.TLiveStatus;
import org.apache.ibatis.jdbc.SQL;

public class TLiveStatusSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_liveStatus
     *
     * @mbg.generated
     */
    public String insertSelective(TLiveStatus record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("v_liveStatus");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_liveStatus
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TLiveStatus record) {
        SQL sql = new SQL();
        sql.UPDATE("v_liveStatus");
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}