package com.example.videohttp.mapper;

import com.example.videohttp.module.TLiveHistory;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TLiveHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_live_history
     *
     * @mbg.generated
     */
    @Delete({
        "delete from v_live_history",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_live_history
     *
     * @mbg.generated
     */
    @Insert({
        "insert into v_live_history (id, userId, ",
        "filePath, createTime)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{filePath,jdbcType=VARCHAR}, #{createTime,jdbcType=VARCHAR})"
    })
    int insert(TLiveHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_live_history
     *
     * @mbg.generated
     */
    @InsertProvider(type=TLiveHistorySqlProvider.class, method="insertSelective")
    int insertSelective(TLiveHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_live_history
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, userId, filePath, createTime",
        "from v_live_history",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userId", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="filePath", property="filePath", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.VARCHAR)
    })
    TLiveHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_live_history
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TLiveHistorySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TLiveHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_live_history
     *
     * @mbg.generated
     */
    @Update({
        "update v_live_history",
        "set userId = #{userId,jdbcType=INTEGER},",
          "filePath = #{filePath,jdbcType=VARCHAR},",
          "createTime = #{createTime,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TLiveHistory record);
}