package com.example.videohttp.mapper;

import com.example.videohttp.module.TLive;
import org.apache.ibatis.jdbc.SQL;

public class TLiveSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_live
     *
     * @mbg.generated
     */
    public String insertSelective(TLive record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("v_live");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("userId", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getLiveTitle() != null) {
            sql.VALUES("liveTitle", "#{liveTitle,jdbcType=VARCHAR}");
        }
        
        if (record.getLiveIcon() != null) {
            sql.VALUES("liveIcon", "#{liveIcon,jdbcType=VARCHAR}");
        }
        
        if (record.getLiveAddress() != null) {
            sql.VALUES("liveAddress", "#{liveAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getLiveStatus() != null) {
            sql.VALUES("liveStatus", "#{liveStatus,jdbcType=INTEGER}");
        }
        
        if (record.getLiveHdAddress() != null) {
            sql.VALUES("liveHdAddress", "#{liveHdAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getLiveSdAddress() != null) {
            sql.VALUES("liveSdAddress", "#{liveSdAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getLiveDescription() != null) {
            sql.VALUES("liveDescription", "#{liveDescription,jdbcType=VARCHAR}");
        }
        
        if (record.getLiveLdAddress() != null) {
            sql.VALUES("liveLdAddress", "#{liveLdAddress,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_live
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TLive record) {
        SQL sql = new SQL();
        sql.UPDATE("v_live");
        
        if (record.getUserId() != null) {
            sql.SET("userId = #{userId,jdbcType=INTEGER}");
        }
        
        if (record.getLiveTitle() != null) {
            sql.SET("liveTitle = #{liveTitle,jdbcType=VARCHAR}");
        }
        
        if (record.getLiveIcon() != null) {
            sql.SET("liveIcon = #{liveIcon,jdbcType=VARCHAR}");
        }
        
        if (record.getLiveAddress() != null) {
            sql.SET("liveAddress = #{liveAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getLiveStatus() != null) {
            sql.SET("liveStatus = #{liveStatus,jdbcType=INTEGER}");
        }
        
        if (record.getLiveHdAddress() != null) {
            sql.SET("liveHdAddress = #{liveHdAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getLiveSdAddress() != null) {
            sql.SET("liveSdAddress = #{liveSdAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getLiveDescription() != null) {
            sql.SET("liveDescription = #{liveDescription,jdbcType=VARCHAR}");
        }
        
        if (record.getLiveLdAddress() != null) {
            sql.SET("liveLdAddress = #{liveLdAddress,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}