package com.example.videohttp.mapper;

import com.example.videohttp.module.TLiveStatus;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TLiveStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_liveStatus
     *
     * @mbg.generated
     */
    @Delete({
        "delete from v_liveStatus",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_liveStatus
     *
     * @mbg.generated
     */
    @Insert({
        "insert into v_liveStatus (id, status)",
        "values (#{id,jdbcType=INTEGER}, #{status,jdbcType=VARCHAR})"
    })
    int insert(TLiveStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_liveStatus
     *
     * @mbg.generated
     */
    @InsertProvider(type=TLiveStatusSqlProvider.class, method="insertSelective")
    int insertSelective(TLiveStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_liveStatus
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, status",
        "from v_liveStatus",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="status", property="status", jdbcType=JdbcType.VARCHAR)
    })
    TLiveStatus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_liveStatus
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TLiveStatusSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TLiveStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_liveStatus
     *
     * @mbg.generated
     */
    @Update({
        "update v_liveStatus",
        "set status = #{status,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TLiveStatus record);
}