package com.example.videohttp.mapper;

import com.example.videohttp.module.TSrs;
import org.apache.ibatis.jdbc.SQL;

public class TSrsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_srs
     *
     * @mbg.generated
     */
    public String insertSelective(TSrs record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("v_srs");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getAction() != null) {
            sql.VALUES("action", "#{action,jdbcType=VARCHAR}");
        }
        
        if (record.getClientId() != null) {
            sql.VALUES("client_id", "#{clientId,jdbcType=INTEGER}");
        }
        
        if (record.getIp() != null) {
            sql.VALUES("ip", "#{ip,jdbcType=VARCHAR}");
        }
        
        if (record.getVhost() != null) {
            sql.VALUES("vhost", "#{vhost,jdbcType=VARCHAR}");
        }
        
        if (record.getApp() != null) {
            sql.VALUES("app", "#{app,jdbcType=VARCHAR}");
        }
        
        if (record.getCustom() != null) {
            sql.VALUES("custom", "#{custom,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatetime() != null) {
            sql.VALUES("createTime", "#{createtime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_srs
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TSrs record) {
        SQL sql = new SQL();
        sql.UPDATE("v_srs");
        
        if (record.getAction() != null) {
            sql.SET("action = #{action,jdbcType=VARCHAR}");
        }
        
        if (record.getClientId() != null) {
            sql.SET("client_id = #{clientId,jdbcType=INTEGER}");
        }
        
        if (record.getIp() != null) {
            sql.SET("ip = #{ip,jdbcType=VARCHAR}");
        }
        
        if (record.getVhost() != null) {
            sql.SET("vhost = #{vhost,jdbcType=VARCHAR}");
        }
        
        if (record.getApp() != null) {
            sql.SET("app = #{app,jdbcType=VARCHAR}");
        }
        
        if (record.getCustom() != null) {
            sql.SET("custom = #{custom,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatetime() != null) {
            sql.SET("createTime = #{createtime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}