package com.example.videohttp.mapper;

import com.example.videohttp.module.TUser;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface TUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    @Delete({
        "delete from v_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into v_user (id, userName, ",
        "userAge, userPhone, ",
        "userEmail, userPassword, ",
        "userCreateTime, userBirthDay)",
        "values (#{id,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
        "#{userage,jdbcType=INTEGER}, #{userphone,jdbcType=VARCHAR}, ",
        "#{useremail,jdbcType=VARCHAR}, #{userpassword,jdbcType=VARCHAR}, ",
        "#{usercreatetime,jdbcType=TIMESTAMP}, #{userbirthday,jdbcType=TIMESTAMP})"
    })
    int insert(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    @InsertProvider(type=TUserSqlProvider.class, method="insertSelective")
    int insertSelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, userName, userAge, userPhone, userEmail, userPassword, userCreateTime, userBirthDay",
        "from v_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userName", property="username", jdbcType=JdbcType.VARCHAR),
        @Result(column="userAge", property="userage", jdbcType=JdbcType.INTEGER),
        @Result(column="userPhone", property="userphone", jdbcType=JdbcType.VARCHAR),
        @Result(column="userEmail", property="useremail", jdbcType=JdbcType.VARCHAR),
        @Result(column="userPassword", property="userpassword", jdbcType=JdbcType.VARCHAR),
        @Result(column="userCreateTime", property="usercreatetime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="userBirthDay", property="userbirthday", jdbcType=JdbcType.TIMESTAMP)
    })
    TUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    @Update({
        "update v_user",
        "set userName = #{username,jdbcType=VARCHAR},",
          "userAge = #{userage,jdbcType=INTEGER},",
          "userPhone = #{userphone,jdbcType=VARCHAR},",
          "userEmail = #{useremail,jdbcType=VARCHAR},",
          "userPassword = #{userpassword,jdbcType=VARCHAR},",
          "userCreateTime = #{usercreatetime,jdbcType=TIMESTAMP},",
          "userBirthDay = #{userbirthday,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TUser record);
    /**
     * 根据用户名和密码查询
     */
    @Select({
            "select",
            "id, userName, userAge, userPhone, userEmail, userPassword",
            "from v_user",
            "where userName = #{userName,jdbcType=VARCHAR} and userPassword=#{userPassword,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="userName", property="username", jdbcType=JdbcType.VARCHAR),
            @Result(column="userAge", property="userage", jdbcType=JdbcType.INTEGER),
            @Result(column="userPhone", property="userphone", jdbcType=JdbcType.VARCHAR),
            @Result(column="userEmail", property="useremail", jdbcType=JdbcType.VARCHAR),
            @Result(column="userPassword", property="userpassword", jdbcType=JdbcType.VARCHAR),
            @Result(column="userCreateTime", property="usercreatetime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="userBirthDay", property="userbirthday", jdbcType=JdbcType.TIMESTAMP)
    })
    TUser selectByUserNameAndPassword(@Param("userName") String userName, @Param("userPassword") String userPassword);
    /**
     * 根据用户名查询
     */
    @Select({
            "select",
            "id, userName, userAge, userPhone, userEmail, userPassword",
            "from v_user",
            "where userName = #{userName,jdbcType=VARCHAR}"
    })
    @Results({
            @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="userName", property="username", jdbcType=JdbcType.VARCHAR),
            @Result(column="userAge", property="userage", jdbcType=JdbcType.INTEGER),
            @Result(column="userPhone", property="userphone", jdbcType=JdbcType.VARCHAR),
            @Result(column="userEmail", property="useremail", jdbcType=JdbcType.VARCHAR),
            @Result(column="userPassword", property="userpassword", jdbcType=JdbcType.VARCHAR),
            @Result(column="userCreateTime", property="usercreatetime", jdbcType=JdbcType.TIMESTAMP),
            @Result(column="userBirthDay", property="userbirthday", jdbcType=JdbcType.TIMESTAMP)
    })
    TUser selectByUserName(@Param("userName") String userName);
}