package com.example.videohttp.mapper;

import com.example.videohttp.module.TUser;
import org.apache.ibatis.jdbc.SQL;

public class TUserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    public String insertSelective(TUser record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("v_user");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUserName() != null) {
            sql.VALUES("userName", "#{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserAge() != null) {
            sql.VALUES("userAge", "#{userAge,jdbcType=INTEGER}");
        }
        
        if (record.getUserPhone() != null) {
            sql.VALUES("userPhone", "#{userPhone,jdbcType=VARCHAR}");
        }
        
        if (record.getUserEmail() != null) {
            sql.VALUES("userEmail", "#{userEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getUserPassword() != null) {
            sql.VALUES("userPassword", "#{userPassword,jdbcType=VARCHAR}");
        }
        
        if (record.getUserCreateTime() != null) {
            sql.VALUES("userCreateTime", "#{userCreateTime,jdbcType=VARCHAR}");
        }
        
        if (record.getUserBirthDay() != null) {
            sql.VALUES("userBirthDay", "#{userBirthDay,jdbcType=VARCHAR}");
        }
        
        if (record.getUserSex() != null) {
            sql.VALUES("userSex", "#{userSex,jdbcType=BIT}");
        }
        
        if (record.getUserIcon() != null) {
            sql.VALUES("userIcon", "#{userIcon,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TUser record) {
        SQL sql = new SQL();
        sql.UPDATE("v_user");
        
        if (record.getUserName() != null) {
            sql.SET("userName = #{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getUserAge() != null) {
            sql.SET("userAge = #{userAge,jdbcType=INTEGER}");
        }
        
        if (record.getUserPhone() != null) {
            sql.SET("userPhone = #{userPhone,jdbcType=VARCHAR}");
        }
        
        if (record.getUserEmail() != null) {
            sql.SET("userEmail = #{userEmail,jdbcType=VARCHAR}");
        }
        
        if (record.getUserPassword() != null) {
            sql.SET("userPassword = #{userPassword,jdbcType=VARCHAR}");
        }
        
        if (record.getUserCreateTime() != null) {
            sql.SET("userCreateTime = #{userCreateTime,jdbcType=VARCHAR}");
        }
        
        if (record.getUserBirthDay() != null) {
            sql.SET("userBirthDay = #{userBirthDay,jdbcType=VARCHAR}");
        }
        
        if (record.getUserSex() != null) {
            sql.SET("userSex = #{userSex,jdbcType=BIT}");
        }
        
        if (record.getUserIcon() != null) {
            sql.SET("userIcon = #{userIcon,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}