package com.example.videohttp.mapper;

import com.example.videohttp.module.TUser;
import org.apache.ibatis.jdbc.SQL;

public class TUserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    public String insertSelective(TUser record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("v_user");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUsername() != null) {
            sql.VALUES("userName", "#{username,jdbcType=VARCHAR}");
        }
        
        if (record.getUserage() != null) {
            sql.VALUES("userAge", "#{userage,jdbcType=INTEGER}");
        }
        
        if (record.getUserphone() != null) {
            sql.VALUES("userPhone", "#{userphone,jdbcType=VARCHAR}");
        }
        
        if (record.getUseremail() != null) {
            sql.VALUES("userEmail", "#{useremail,jdbcType=VARCHAR}");
        }
        
        if (record.getUserpassword() != null) {
            sql.VALUES("userPassword", "#{userpassword,jdbcType=VARCHAR}");
        }
        
        if (record.getUsercreatetime() != null) {
            sql.VALUES("userCreateTime", "#{usercreatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUserbirthday() != null) {
            sql.VALUES("userBirthDay", "#{userbirthday,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUsersex() != null) {
            sql.VALUES("userSex", "#{usersex,jdbcType=BIT}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TUser record) {
        SQL sql = new SQL();
        sql.UPDATE("v_user");
        
        if (record.getUsername() != null) {
            sql.SET("userName = #{username,jdbcType=VARCHAR}");
        }
        
        if (record.getUserage() != null) {
            sql.SET("userAge = #{userage,jdbcType=INTEGER}");
        }
        
        if (record.getUserphone() != null) {
            sql.SET("userPhone = #{userphone,jdbcType=VARCHAR}");
        }
        
        if (record.getUseremail() != null) {
            sql.SET("userEmail = #{useremail,jdbcType=VARCHAR}");
        }
        
        if (record.getUserpassword() != null) {
            sql.SET("userPassword = #{userpassword,jdbcType=VARCHAR}");
        }
        
        if (record.getUsercreatetime() != null) {
            sql.SET("userCreateTime = #{usercreatetime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUserbirthday() != null) {
            sql.SET("userBirthDay = #{userbirthday,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUsersex() != null) {
            sql.SET("userSex = #{usersex,jdbcType=BIT}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}