package com.example.videohttp.mapper;

import com.example.videohttp.module.TUser;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    @Delete({
        "delete from v_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    @Insert({
        "insert into v_user (id, userName, ",
        "userAge, userPhone, ",
        "userEmail, userPassword, ",
        "userCreateTime, userBirthDay, ",
        "userSex, userIcon)",
        "values (#{id,jdbcType=INTEGER}, #{userName,jdbcType=VARCHAR}, ",
        "#{userAge,jdbcType=INTEGER}, #{userPhone,jdbcType=VARCHAR}, ",
        "#{userEmail,jdbcType=VARCHAR}, #{userPassword,jdbcType=VARCHAR}, ",
        "#{userCreateTime,jdbcType=VARCHAR}, #{userBirthDay,jdbcType=VARCHAR}, ",
        "#{userSex,jdbcType=BIT}, #{userIcon,jdbcType=VARCHAR})"
    })
    int insert(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    @InsertProvider(type=TUserSqlProvider.class, method="insertSelective")
    int insertSelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, userName, userAge, userPhone, userEmail, userPassword, userCreateTime, userBirthDay, ",
        "userSex, userIcon",
        "from v_user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="userName", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="userAge", property="userAge", jdbcType=JdbcType.INTEGER),
        @Result(column="userPhone", property="userPhone", jdbcType=JdbcType.VARCHAR),
        @Result(column="userEmail", property="userEmail", jdbcType=JdbcType.VARCHAR),
        @Result(column="userPassword", property="userPassword", jdbcType=JdbcType.VARCHAR),
        @Result(column="userCreateTime", property="userCreateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="userBirthDay", property="userBirthDay", jdbcType=JdbcType.VARCHAR),
        @Result(column="userSex", property="userSex", jdbcType=JdbcType.BIT),
        @Result(column="userIcon", property="userIcon", jdbcType=JdbcType.VARCHAR)
    })
    TUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TUserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_user
     *
     * @mbg.generated
     */
    @Update({
        "update v_user",
        "set userName = #{userName,jdbcType=VARCHAR},",
          "userAge = #{userAge,jdbcType=INTEGER},",
          "userPhone = #{userPhone,jdbcType=VARCHAR},",
          "userEmail = #{userEmail,jdbcType=VARCHAR},",
          "userPassword = #{userPassword,jdbcType=VARCHAR},",
          "userCreateTime = #{userCreateTime,jdbcType=VARCHAR},",
          "userBirthDay = #{userBirthDay,jdbcType=VARCHAR},",
          "userSex = #{userSex,jdbcType=BIT},",
          "userIcon = #{userIcon,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TUser record);
}