package com.example.videohttp.mapper;

import com.example.videohttp.module.TVideo;
import org.apache.ibatis.jdbc.SQL;

public class TVideoSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_video
     *
     * @mbg.generated
     */
    public String insertSelective(TVideo record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("v_video");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getPath() != null) {
            sql.VALUES("path", "#{path,jdbcType=VARCHAR}");
        }
        
        if (record.getUserid() != null) {
            sql.VALUES("userid", "#{userid,jdbcType=INTEGER}");
        }
        
        if (record.getCoverPath() != null) {
            sql.VALUES("coverPath", "#{coverPath,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_video
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TVideo record) {
        SQL sql = new SQL();
        sql.UPDATE("v_video");
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getPath() != null) {
            sql.SET("path = #{path,jdbcType=VARCHAR}");
        }
        
        if (record.getUserid() != null) {
            sql.SET("userid = #{userid,jdbcType=INTEGER}");
        }
        
        if (record.getCoverPath() != null) {
            sql.SET("coverPath = #{coverPath,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}