package com.example.videohttp.mapper;

import com.example.videohttp.module.TVideo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface TVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_video
     *
     * @mbg.generated
     */
    @Delete({
        "delete from v_video",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_video
     *
     * @mbg.generated
     */
    @Insert({
        "insert into v_video (id, name, ",
        "path, userid, coverPath)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{path,jdbcType=VARCHAR}, #{userid,jdbcType=INTEGER}, #{coverPath,jdbcType=VARCHAR})"
    })
    int insert(TVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_video
     *
     * @mbg.generated
     */
    @InsertProvider(type=TVideoSqlProvider.class, method="insertSelective")
    int insertSelective(TVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_video
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, name, path, userid, coverPath",
        "from v_video",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="path", property="path", jdbcType=JdbcType.VARCHAR),
        @Result(column="userid", property="userid", jdbcType=JdbcType.INTEGER),
        @Result(column="coverPath", property="coverPath", jdbcType=JdbcType.VARCHAR)
    })
    TVideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_video
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TVideoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_video
     *
     * @mbg.generated
     */
    @Update({
        "update v_video",
        "set name = #{name,jdbcType=VARCHAR},",
          "path = #{path,jdbcType=VARCHAR},",
          "userid = #{userid,jdbcType=INTEGER},",
          "coverPath = #{coverPath,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TVideo record);
}